---

- name: Install nfs utils
  ansible.builtin.apt:
    pkg: "{{ item }}"
    state: present
  with_items:
    - nfs-common
    - autofs
    - rpcbind

- name: Ensure rpcbind service is running
  ansible.builtin.service:
    name: Rpcbind
    state: started
    enabled: yes
