---

- name: Start rpcbind
  ansible.builtin.service:
    name: Rpcbind
    state: started

- name: Reload rpcbind
  ansible.builtin.service:
    name: Rpcbind
    state: reloaded

- name: Restart rpcbind
  ansible.builtin.service:
    name: Rpcbind
    state: restarted
    enabled: true

- name: Stop rpcbind
  ansible.builtin.service:
    name: Rpcbind
    state: stopped
